version: "3.7" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  db: # 서비스 명
    platform: linux/x86_64
    image: mysql:8.0.23 # 사용할 이미지
    restart: always
    container_name: couple # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - MYSQL_DATABASE=couple
      - MYSQL_ROOT_PASSWORD=dpstldzm
      - TZ=Asia/Seoul
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=mildangdev1357
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=NO_ENGINE_SUBSTITUTION

    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
